services:
  instapaper-fetcher:
    build: https://github.com/h13/instapaper-fetcher.git
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    command: php -S 0.0.0.0:8081 -t public/
    networks:
      - podcast-network

  text-summarizer:
    build: https://github.com/h13/text-summarizer.git
    ports:
      - "8082:8082"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    command: php -S 0.0.0.0:8082 -t public/
    networks:
      - podcast-network
    depends_on:
      - instapaper-fetcher

  text-to-speech:
    build: https://github.com/h13/text-to-speech.git
    ports:
      - "8083:8083"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    command: php -S 0.0.0.0:8083 -t public/
    networks:
      - podcast-network
    depends_on:
      - text-summarizer

  podcast-publisher:
    build: https://github.com/h13/podcast-publisher.git
    ports:
      - "8084:8084"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    command: php -S 0.0.0.0:8084 -t public/
    networks:
      - podcast-network
    depends_on:
      - text-to-speech

networks:
  podcast-network:
    driver: bridge